wsd_framework_dir: data/WSD_Evaluation_Framework

# sense inventory
sense_inventory:
  _target_: src.sense_inventories.WordNetSenseInventory
  wn_candidates_path: ${callbacks.wsd_framework_dir}/Data_Validation/candidatesWN30.txt

callbacks:
  - _target_: src.pl_callbacks.PredictorsRaganatoEvaluateCallback
    raganato_path: ${callbacks.wsd_framework_dir}/Evaluation_Datasets/semeval2007/semeval2007
    wsd_framework_dir: ${callbacks.wsd_framework_dir}
    samples_generator:
      _target_: src.consec_dataset.build_samples_generator_from_disambiguation_corpus
      disambiguation_corpus:
        _target_: src.disambiguation_corpora.WordNetCorpus
        raganato_path: ${callbacks.wsd_framework_dir}/Evaluation_Datasets/semeval2007/semeval2007  # todo should ref here the above raganato path (how to do it with hydra?)
        materialize: True
        cached: False
      sense_inventory: ${callbacks.sense_inventory}
      sentence_window: 2  # one prev one next
      randomize_sentence_window: False
      remove_multilabel_instances: False
      shuffle_definitions: False
      randomize_dependencies: False
    predictors:
      teacher_forced_ppmi:
        _target_: src.scripts.model.continuous_predict.TeacherForcedPredictor
        dependency_finder:
          _target_: src.dependency_finder.PPMIPolysemyDependencyFinder
          sense_inventory: ${callbacks.sense_inventory}
          single_counter_path: data/pmi/lemma_counter.txt
          pair_counter_path: data/pmi/pairs_counter.txt
          energy: 0.7
          max_dependencies: 9
          normalize_ppmi: True
          minimum_ppmi: 0.1
      greedy_ppmi:
        _target_: src.scripts.model.continuous_predict.GreedyDepPredictor
        dependency_finder:
          _target_: src.dependency_finder.PPMIPolysemyDependencyFinder
          sense_inventory: ${callbacks.sense_inventory}
          single_counter_path: data/pmi/lemma_counter.txt
          pair_counter_path: data/pmi/pairs_counter.txt
          energy: 0.7
          max_dependencies: 9
          normalize_ppmi: True
          minimum_ppmi: 0.1
    wordnet_sense_inventory:
      _target_: src.sense_inventories.WordNetSenseInventory
      wn_candidates_path: ${callbacks.wsd_framework_dir}/Data_Validation/candidatesWN30.txt
    prediction_params:
      text_encoding_strategy: "relative-positions"
      token_batch_size: 4096
      progress_bar: False
  - _target_: src.pl_callbacks.PredictorsRaganatoEvaluateCallback
    raganato_path: data/complemented-datasets/semeval2007/semeval2007
    wsd_framework_dir: ${callbacks.wsd_framework_dir}
    samples_generator:
      _target_: src.consec_dataset.build_samples_generator_from_disambiguation_corpus
      disambiguation_corpus:
        _target_: src.disambiguation_corpora.WordNetCorpus
        raganato_path: data/complemented-datasets/semeval2007/semeval2007  # todo should ref here the above raganato path (how to do it with hydra?)
        materialize: True
        cached: False
      sense_inventory: ${callbacks.sense_inventory}
      sentence_window: 2  # one prev one next
      randomize_sentence_window: False
      remove_multilabel_instances: False
      shuffle_definitions: False
      randomize_dependencies: False
    predictors:
      unannotated_greedy_ppmi:
        _target_: src.scripts.model.continuous_predict.GreedyDepPredictor
        dependency_finder:
          _target_: src.dependency_finder.PPMIPolysemyDependencyFinder
          sense_inventory: ${callbacks.sense_inventory}
          single_counter_path: data/pmi/lemma_counter.txt
          pair_counter_path: data/pmi/pairs_counter.txt
          energy: 0.7
          max_dependencies: 9
          normalize_ppmi: True
          minimum_ppmi: 0.1
#      unannotated_beam20_ppmi:
#        _target_: src.scripts.model.continuous_predict.BeamDepPredictor
#        beam_size: 20
#        enable_reporting: False
#        dependency_finder:
#          _target_: src.dependency_finder.PPMIPolysemyDependencyFinder
#          sense_inventory: ${callbacks.sense_inventory}
#          single_counter_path: data/pmi/lemma_counter.txt
#          pair_counter_path: data/pmi/pairs_counter.txt
#          max_dependencies: 9
#          energy: 0.7
#          normalize_ppmi: True
#          minimum_ppmi: 0.1
    wordnet_sense_inventory:
      _target_: src.sense_inventories.WordNetSenseInventory
      wn_candidates_path: ${callbacks.wsd_framework_dir}/Data_Validation/candidatesWN30.txt
    prediction_params:
      text_encoding_strategy: "relative-positions"
      token_batch_size: 4096
      progress_bar: False
